project:
  type: website
  output-dir: docs

website:
  title: "./"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Untitled.qmd
        text: Presentation

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



